Repository trustbloc/k8s, pull requests merged in 2021-11, with the labels that each got.

#254 fix: orb healthcheck URL
  orb/kustomize/orb/base/deployment.yml
  orb/kustomize/orb/overlays/local/setup/add-followers.yml
Labels: cla-signed

#255 refactor: roll-back ORB healthcheck URL in init containers
  orb/kustomize/orb/overlays/local/setup/add-followers.yml
Labels: cla-signed

#257 refactor: mq remove component label
  orb/kustomize/orb/components/mq/kustomization.yaml
Labels: cla-signed

#258 chore: kms create common aggrigate
  kms/kustomize/kms/overlays/common/kustomization.yaml
Labels: cla-signed

#256 chore: orb-driver align common overlay path
  orb-driver/kustomize/orb-driver/overlays/common/config.env
  orb-driver/kustomize/orb-driver/overlays/common/kustomization.yaml
  orb-driver/kustomize/orb-driver/overlays/common/sedtransform.yml
  orb-driver/kustomize/orb-driver/overlays/local/orb-driver/kustomization.yaml
Labels: cla-signed

#260 chore: update to latest wallet
  wallet-server/Makefile
  wallet-server/kustomize/wallet-server/base/kustomization.yaml
  wallet-web/Makefile
  wallet-web/kustomize/wallet-web/base/kustomization.yaml
Labels: cla-signed

#261 chore: update to latest wallet
  wallet-server/Makefile
  wallet-server/kustomize/wallet-server/base/kustomization.yaml
  wallet-web/Makefile
  wallet-web/kustomize/wallet-web/base/kustomization.yaml
Labels: cla-signed

#262 chore: update to latest wallet
  wallet-server/Makefile
  wallet-server/kustomize/wallet-server/base/kustomization.yaml
  wallet-web/Makefile
  wallet-web/kustomize/wallet-web/base/kustomization.yaml
Labels: cla-signed

#263 chore: update to latest wallet
  wallet-server/Makefile
  wallet-server/kustomize/wallet-server/base/kustomization.yaml
  wallet-web/Makefile
  wallet-web/kustomize/wallet-web/base/kustomization.yaml
Labels: cla-signed

#264 chore: update to latest wallet
  wallet-server/Makefile
  wallet-server/kustomize/wallet-server/base/kustomization.yaml
  wallet-web/Makefile
  wallet-web/kustomize/wallet-web/base/kustomization.yaml
Labels: cla-signed

#265 chore: update to latest wallet
  wallet-server/Makefile
  wallet-server/kustomize/wallet-server/base/kustomization.yaml
  wallet-web/Makefile
  wallet-web/kustomize/wallet-web/base/kustomization.yaml
Labels: cla-signed

#267 chore: update to latest wallet
  wallet-server/Makefile
  wallet-server/kustomize/wallet-server/base/kustomization.yaml
  wallet-web/Makefile
  wallet-web/kustomize/wallet-web/base/kustomization.yaml
Labels: cla-signed

#268 chore: update to latest agent sdk
  wallet-server/Makefile
  wallet-server/kustomize/wallet-server/base/kustomization.yaml
  wallet-web/Makefile
  wallet-web/kustomize/wallet-web/base/kustomization.yaml
Labels: cla-signed

#269 chore: update kubectl version to 1.21.2
  adapter-issuer/Makefile
  adapter-rp/Makefile
  csh/Makefile
  dbs/Makefile
  edv/Makefile
  hub-auth/Makefile
  hub-router/Makefile
  kms/Makefile
  orb/Makefile
  registrar/Makefile
  resolver/Makefile
  vault-server/Makefile
  vcs/Makefile
  vct/Makefile
  wallet-server/Makefile
  wallet-web/Makefile
Labels: recurring, infrastructure

#259 docs: update to minikube 1.24.0
  README.md
Labels: documentation, cla-signed, infrastructure

#270 chore: remove use orb tag cli
  orb/kustomize/orb/overlays/local/setup/create_follow_activity.sh
Labels: cla-signed

#271 chore: update to latest wallet
  wallet-server/Makefile
  wallet-server/kustomize/wallet-server/base/kustomization.yaml
  wallet-web/Makefile
  wallet-web/kustomize/wallet-web/base/config.env
  wallet-web/kustomize/wallet-web/base/default.conf.template
  wallet-web/kustomize/wallet-web/base/kustomization.yaml
Labels: cla-signed

#273 chore: update to latest wallet
  wallet-server/Makefile
  wallet-server/kustomize/wallet-server/base/kustomization.yaml
  wallet-web/Makefile
  wallet-web/kustomize/wallet-web/base/kustomization.yaml
Labels: cla-signed

#277 chore: update to latest walley
  wallet-server/Makefile
  wallet-server/kustomize/wallet-server/base/kustomization.yaml
  wallet-web/Makefile
  wallet-web/kustomize/wallet-web/base/kustomization.yaml
Labels: cla-signed

#278 chore: update to latest orb
  orb-driver/Makefile
  orb-driver/kustomize/orb-driver/base/kustomization.yaml
  orb/Makefile
  orb/kustomize/orb/base/kustomization.yaml
  orb/kustomize/orb/overlays/common/orb/config.env
Labels: cla-signed

#280 Revert "chore: remove orb config flags"
  orb/kustomize/orb/overlays/common/orb/config.env
Labels: cla-signed

#281 chore: update orb
  orb-driver/Makefile
  orb-driver/kustomize/orb-driver/base/kustomization.yaml
  orb/Makefile
  orb/kustomize/orb/base/kustomization.yaml
  orb/kustomize/orb/overlays/common/orb/config.env
Labels: cla-signed

#282 chore: update k8s with the latest wallet
  wallet-server/Makefile
  wallet-server/kustomize/wallet-server/base/kustomization.yaml
  wallet-web/Makefile
  wallet-web/kustomize/wallet-web/base/kustomization.yaml
Labels: cla-signed

#284 chore: update to latest orb
  orb-driver/Makefile
  orb-driver/kustomize/orb-driver/base/kustomization.yaml
  orb/Makefile
  orb/kustomize/orb/base/kustomization.yaml
Labels: cla-signed

#285 chore: fix orb flags
  orb/kustomize/orb/overlays/common/orb/config.env
Labels: cla-signed

#286 chore: change anchor origin wallet to orb-1
  wallet-web/kustomize/wallet-web/overlays/common/config.env
Labels: cla-signed

#289 feat: add traceability context
  dbs/kustomize/dbs/components/static-file-server/ld-contexts.json
Labels: cla-signed

#291 chore: update vc server
  vcs/Makefile
  vcs/kustomize/vcs/overlays/common/governance/config.env
  vcs/kustomize/vcs/overlays/common/holder/config.env
  vcs/kustomize/vcs/overlays/common/issuer/config.env
  vcs/kustomize/vcs/overlays/common/verifier/config.env
Labels: cla-signed

#292 chore: update orb to latest
  orb-driver/Makefile
  orb-driver/kustomize/orb-driver/base/kustomization.yaml
  orb/Makefile
  orb/kustomize/orb/base/kustomization.yaml
Labels: cla-signed

#294 chore: update to latest orb
  orb-driver/Makefile
  orb-driver/kustomize/orb-driver/base/kustomization.yaml
  orb/Makefile
  orb/kustomize/orb/base/kustomization.yaml
Labels: cla-signed

#295 chore: updated k8s with the latest wallet
  wallet-server/Makefile
  wallet-server/kustomize/wallet-server/base/kustomization.yaml
  wallet-web/Makefile
  wallet-web/kustomize/wallet-web/base/kustomization.yaml
Labels: cla-signed
